# Generated by Django 5.0.4 on 2024-04-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Link', models.CharField(max_length=500)),
                ('Notes', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('Purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource_Library_Register.purpose')),
            ],
        ),
    ]
